
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./logs:/mmogame/logs
    environment:
      - FLASK_RUN_PORT=8080
      - DOCKER_DB=true
    depends_on:
      - mongo  

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
